version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./php
        ports:
            - "9000:9000"
        volumes:
            - ./:/www
        links:
            - db
    nginx:
        image: nginx
        ports:
          - "8080:80"
        links:
            - php
        volumes_from:
            - php
        volumes:
          - ./nginx.conf:/etc/nginx/conf.d/default.conf